### ISSUE TITLE
Style: loading screen and fade-in can be disruptive

### ISSUE THREAD

**Issue by stefanv** [scipy/scipy-sphinx-theme-v2#47]
I find the fade-in screen on every load, and *every click followed* very disturbing.  What do others think?  I would prefer a page that... just loads.

**Comment by stefanv** [comment]
I should mention that, more distractingly, the page sometimes loads *after which* the fade-in happens.

**Comment by rgommers** [comment]
I think that's Surge, not the theme. It happens for the new NumPy website too on Surge, but not locally.

**Comment by stefanv** [comment]
Thanks, good to know!
