### ISSUE TITLE
Style: Padding in search results seems excessive

### ISSUE THREAD

**Issue by fuglede** [scipy/scipy-sphinx-theme-v2#65]
Comparing the search result page from before with the new one, a very large amount of padding has been added to the individual items. This means that a much smaller amount of search results appear per screen height, which seems like a step backwards.

Below are examples of a single search:

Before:
![before](https://user-images.githubusercontent.com/6169306/69734882-0a789b00-1130-11ea-8859-4ce380424c8e.png)

Now:
![now](https://user-images.githubusercontent.com/6169306/69734894-0e0c2200-1130-11ea-85a0-d540096ed210.png)

**Comment by Shekharrajak** [comment]
Thanks for noting it down.
