### ISSUE TITLE
Left-side navigation panel does not wrap text

### ISSUE THREAD

**Issue by justbennet** [scipy/scipy-sphinx-theme-v2#67]
The table of contents on the left that contains the Search docs box seems to have its width set to be proportional to browser window width.  When I narrow the browser window width, the text in the table of contents does not wrap as the menu's width narrows; instead items are truncated, until one gets to a width where the table of contents disappears altogether into an item at the top of the body page.

This is what I get

![image](https://user-images.githubusercontent.com/1595586/69820540-4ca4e980-11cf-11ea-9f91-1f0175484a63.png)

as a consequence.

It might be nice to make the text wrap rather than truncate (or perhaps better, make the TOC a fixed width until it goes into hiding)?  I think that the size at which it hides should be decreased as well.  To keep the TOC, my browser window has to be about 2/3 of the screen width, which will possibly interfere with people who want the docs next to an editor on the same screen.

There are people who still work on 17" and 19" screens who will appreciate that change.  I know, not many of us, but some.

**Comment by Shekharrajak** [comment]
Thanks for noting down this issue. 

Actually menu should be like this when "table of content" button is visible:

<img width="385" alt="Screenshot 2019-11-29 at 9 01 04 PM" src="https://user-images.githubusercontent.com/5774448/69878592-64719000-12eb-11ea-8d68-8b97a767d121.png">

>There are people who still work on 17" and 19" screens who will appreciate that change. I know, not many of us, but some.

I have checked for the standard device size.Please let me know the width and length for the device where you find issue. I am also looking into the responsiveness of the site.

**Comment by justbennet** [comment]
@Shekharrajak Thanks for your reply.  I use a Dell 24" monitor at 1920x1200 on Ubuntu 18.04 with the Cinnamon desktop.

When I am working on some code, I typically have at least one terminal window open at a default width of 80 columns (and everyone laughs at me for how narrow I keep my terminals).  This is what it looks like if I split the vertical width in half, with one side for the browser and one for the terminal.

![image](https://user-images.githubusercontent.com/1595586/69880853-264b8080-1299-11ea-8bcb-1753180aa56c.png)

Resetting the terminal to an 80 column width, and stretching the browser till I get both the left-side and right-side menus, about 8 columns of the terminal are obscured.

![image](https://user-images.githubusercontent.com/1595586/69881004-8f32f880-1299-11ea-96d1-d39f15a4bfdd.png)

If I resize the browser to not obscure the terminal window, I get this version.

![image](https://user-images.githubusercontent.com/1595586/69881052-bee20080-1299-11ea-9056-15d7afd74b6a.png)

Note that, the blue panel on the left is what I refer to here as the Table of contents; perhaps that is not the correct terminology.

I guess the thing in the upper right with three horizontal lines is the Menu icon?

In any event, what I am concerned about is the width of the Table of Contents that has the blue background and that gets swallowed into

![image](https://user-images.githubusercontent.com/1595586/69881263-72e38b80-129a-11ea-8ee8-309ba0c99fc6.png)

when the browser window gets too narrow.  It looks like that appears when the right-side menu first disappears.

As you can see from the following screen, the entries in the blue-background TOC get truncated before that TOC disappears.

![image](https://user-images.githubusercontent.com/1595586/69881440-0e74fc00-129b-11ea-8f60-43da923fe9f3.png)

As you can see the word Documentation in THEME DOCUMENTATION is cut off, as is scipy.interpolate.griddata

In my work, I have usually set a fixed width for my left-side menu, and allow the right (or perhaps middle and right) to have the rest.  I don't know whether you would consider that appropriate for this project or not, but it seems to work well.

This is what it looks like when nothing in the menu wraps.

![image](https://user-images.githubusercontent.com/1595586/69881691-c86c6800-129b-11ea-9b0c-d97baaae1ced.png)

and my system is reporting that to be 269x491, perhaps a width of 300 px might be a useful starting point?  

My windows do not display their actual sizes (except the terminal window, which does so by columns and not pixels, which I think is not so helpful), so I can report in px width how wide it would be.  There are also many other variables, such as whether the user has invoked font magnification, etc.

I hope something in this reply has been useful.

I do not envy you this job!  Please let me know if I can be of help.

**Comment by Shekharrajak** [comment]
Thanks @justbennet for the screenshot. I understood the concern. I have seen  this issue sometime back but that time I was focusing on standard mobile device, tablet, desktop and laptop size.  

I will work on it. If someone else want to pick this, they are welcome too.

**Comment by Shekharrajak** [comment]
@justbennet, please check the PR: #72 and let me know if you still find the issue.  Demo URL is : https://pr-72-scipy-sphinx-theme-v2.surge.sh/

**Comment by justbennet** [comment]
The left-side menu text wraps, but if you will note, the section headings in the menu bar still truncate when the left side shrinks to a width smaller than their extent.

So, we now get
```
scipy.interpolate.gri
ddata
```
instead of 
```
scipy.interpolate.gri
```
but it still reads
```
THEME DOCUMENTATI
```
as the first heading.  Not sure how to handle this.  If you can define a 'hyphenation character' as you can in TeX, then defining `.` as a suitable break would make the word breaking for function names better.  Not sure what to suggest for the headings other than setting an appropriate minimum width...?

Thanks for working on this!

**Comment by Shekharrajak** [comment]
> but it still reads
> 
> ```
> THEME DOCUMENTAT
> ```

Now it shows the `THEME DOC..` whenever there is overflow in heading. In otherplaces workd break will happen. I think it should be fine (?)

**Comment by justbennet** [comment]
Ah, I missed that first time.  Sure, if that's fine.

**Comment by Shekharrajak** [comment]
Thanks for the review.

**Comment by rgommers** [comment]
@Shekharrajak is there anything left to do here after gh-72, or can we close this issue?

**Comment by Shekharrajak** [comment]
Yup, we can close it.
