### ISSUE TITLE
Text spread over too much horizontal space

### ISSUE THREAD

**Issue by peterbell10** [scipy/scipy-sphinx-theme-v2#68]
Viewing the website on a 1440p monitor with firefox maximised, the text is spread out over too much horizontal space making it awkward to read.

![scipy_sphinx_theme](https://user-images.githubusercontent.com/13238737/69886537-5109f900-12da-11ea-98ab-a0a7dddac146.png)

Compare this to readthedocs' theme which limits the maximum width, keeping content closer together and easier to read (although I would prefer if everything was centred)
![readthedocs](https://user-images.githubusercontent.com/13238737/69886653-f1f8b400-12da-11ea-8770-972a7f133daf.png)

**Comment by Shekharrajak** [comment]
Thanks for sharing the screenshot. Yes! It would be better if we make specific maximum fixed width for body content. Previously I was focusing on how to use the whole width to display the content.

**Comment by fuglede** [comment]
Note that this is the first half of #58 as well, but that one has been marked as fixed.

**Comment by Shekharrajak** [comment]
Max width is set: #73 

<img width="1578" alt="Screenshot 2020-01-12 at 12 56 02 PM" src="https://user-images.githubusercontent.com/5774448/72215607-e5eb4d80-353a-11ea-8d33-af76c78e2030.png">

**Comment by Shekharrajak** [comment]
@fuglede can you please review and check the demo url: https://pr-73-scipy-sphinx-theme-v2.surge.sh/ for the PR #73

**Comment by fuglede** [comment]
Sure. I think it's much better! One thing that did strike me was that the blue side bar feels a bit "floaty", but I'm sure I'm just biased by how Read The Docs normally looks, and how it's left-aligned by default.

**Comment by Shekharrajak** [comment]
Thanks for the review and comment @fuglede ! The base theme is Read The Doc and it is customized to fulfill the NumPy Doc requirement. I am closing this now. 
Feel free to open it if you want to discuss anything else.
