### ISSUE TITLE
Add a License?

### ISSUE THREAD

**Issue by dgrahn** [scipy/scipy-sphinx-theme-v2#76]
Hi!

Could you please add a license to this repository? Ideally, it would be available for use/modification by other projects.

**Comment by rgommers** [comment]
We can add a license file if that's useful. Note that this code is already distributed as part of SciPy releases under the BSD-3 license, so please feel free to reuse any code you like.

We expect to stop using this theme and move to https://github.com/pydata/pydata-sphinx-theme, so I wouldn't recommend adopting this theme for new projects.

**Comment by dgrahn** [comment]
No need to add it. The distribution is fine. It's hard to tell what them the site was using and I thought I found it!

**Comment by rgommers** [comment]
Yes the scipy.org site uses this theme too - another thing we have to throw away and completely rebuild .....
